### ISSUE TITLE
Mistake in a image path

### ISSUE THREAD

**Issue by Zethess** [Drougnov/huddle-landing-page-with-curved-sections-master#1]
Good afternoon mate, I was looking at your code and I noticed that the footer logo was not loading. I have reviewed your code and I saw that you are missing a "." in front of the "/" that makes the image does not load well, on line 98 of the html.

https://github.com/Drougnov/huddle-landing-page-with-curved-sections-master/blame/53d85229ee4718e6e49fd1a3a33b8e07e0e085c5/index.html#L98

Best Regards

**Comment by Drougnov** [comment]
Hey,

Thanks a lot for pointing out the issue in my code. I totally missed that "." in front of the "/". My bad!

I'll fix it right away.

**Comment by Zethess** [comment]
Glad to be of help, mate
